# 1. Numpy Array

In [3]:
import numpy as np
a=np.array([1,2,3])
type(a)

numpy.ndarray

In [4]:
a.shape

(3,)

In [5]:
a[0]

1

In [6]:
a[1]

2

In [7]:
a[2]

3

In [16]:
a[0]=5
print(a)

[[5 5]
 [0 0]]


# Rank 2 array

In [5]:
import numpy as np
b= np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])
b.shape             

(3, 5)

In [10]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 6


In [14]:
a=np.array([[0,0],
          [0,0]])
print(a)


[[0 0]
 [0 0]]


In [15]:
b=np.array([1,1])
print(b)

[1 1]


In [19]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [20]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [34]:
c=np.array([[7,7],[7,7]])
print(c)

[[7 7]
 [7 7]]


In [27]:
d=np.identity(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [30]:
from numpy import random
e=random.rand(2,2)
print(e)

[[0.70735399 0.86910755]
 [0.27242738 0.45156342]]


# 2. array indexing

a) slicing

In [38]:
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])
b=a[0:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [41]:
print(a[0,1])

2


In [44]:
b[0,0]=77
print(a[0,1])

77


In [16]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
row_r1=a[1,:]
row_r2=a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)   

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


1

In [15]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


2

B) Integer array indexing

In [84]:
a = np.array([[1,2], 
              [3, 4],
              [5, 6]])
[a[0,0],a[1,1],a[2,0]]

[1, 4, 5]

In [82]:
print(a[[0, 0], [1, 1]])

[2 2]


In [83]:
print(np.array([a[0, 1], a[0, 1]]))

[2 2]


In [85]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
b = np.array([0, 2, 0, 1])
b[0]

0

In [7]:
b[1]

2

In [8]:
b[2]

0

In [9]:
b[3]

1

In [14]:
b[1]=b[1]+10
b[1]

12

In [15]:
print(b)

[ 0 12  0  1]


c) boolean array indexing

In [19]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = a>2
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [34]:
print(a[bool_idx])

[3 4 5 6]


In [33]:
bool_idx=a>2

In [31]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[a > 2])

[3 4 5 6]


# 3.Datatypes

In [35]:
x = np.array([1, 2])
print(x.dtype)

int32


In [36]:
x = np.array([1.0, 2.0]) 
print(x.dtype)


float64


In [37]:
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64


# 4.Array Math

In [39]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
sum=x+y
print(sum)

[[ 6.  8.]
 [10. 12.]]


In [43]:
diff=x-y
print(diff)

[[-4. -4.]
 [-4. -4.]]


In [46]:
prod=x*y
print(prod)

[[ 5. 12.]
 [21. 32.]]


In [47]:
sqrx=x**2
print(sqrx)

[[ 1.  4.]
 [ 9. 16.]]


In [8]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
innerproduct=np.dot(v,w)
print(innerproduct)

219


In [12]:
vectorproduct=np.cross(x,y)
print(vectorproduct)

[-4 -4]


In [14]:
matrixproduct=np.dot(x,y)
print(matrixproduct)

[[19 22]
 [43 50]]


In [18]:
x = np.array([[1,2],[3,4]])
sum1=np.sum(x)
print(sum1)

10


In [20]:
x = np.array([[1,2]
            ,[3,4]])
columnsum=np.sum(x,axis=0)
print(columnsum)

[4 6]


In [22]:
rowsum=np.sum(x,axis=1)
print(rowsum)

[3 7]


In [23]:
x = np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [26]:
transposeofx=np.transpose(x)
print(transposeofx)

[[1 3]
 [2 4]]


In [27]:
v = np.array([1,2,3])
print(v)

[1 2 3]


In [31]:
transv=np.transpose(v)
print(transv)

[1 2 3]


# 5.Broadcasting

In [37]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
for i in range(4):
    y[i,:]=x[i,:]+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [66]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv= np.tile(v,(4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [72]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [76]:
y=vv+x
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
adding v to each row of x using broadcasting

In [6]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y=np.add(v,x)
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [7]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
outerproduct=np.outer(v,w)
print(outerproduct)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [8]:
x = np.array([[1,2,3], [4,5,6]])
addvx=np.add(v,x)
print(addvx)

[[2 4 6]
 [5 7 9]]


In [10]:
x = np.array([[1,2,3], [4,5,6]])
w = np.array([4,5])
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [12]:
x = np.array([[1,2,3], [4,5,6]])
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]


# 7.Conclusion

In [ ]:
Here i learned many things from numpy.And this assignment is very useful for me.